


stages:
  - build
  - deploy

build bookefy-front:
  stage: build
  image: node:12-alpine
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - dist
  tags:
    - bookefy-front
  script:
    - npm install
    - npm run build

deploy bookefy-front:
  stage: deploy
  only:
    refs:
      - main # main branch for production pipeline
  tags:
    - bookefy-front
  script:
    - mkdir -p ~/front-deployment
    - rm -rf ~/front-deployment/*
    - cp -r dist/. ~/front-deployment

